server:
  port: 8080

spring:
  ai:
    zhipuai:
      api-key: 7b8a15f57d2941a69fcce60f49f7c6ff.SiMrZjCdyOmdtzLr
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.5-flash
          temperature: 0.7
          max-tokens: 2000
